openapi: 3.0.1
info:
  contact:
    email: apiteam@ksco.co
  description: KSCO API
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  termsOfService: http://ksco.co/terms/
  title: Swagger KSCO Ecommerce
  version: 0.0.1
servers:
- url: https://http://localhost:8080/api/v1/
- url: http://http://localhost:8080/api/v1/
paths:
  /user:
    get:
      operationId: loggedInUser
      responses:
        "200":
          content: {}
          description: Returns true/false
      summary: User is logged in
      tags:
      - user
      x-accepts: application/json
  /registration:
    post:
      operationId: registration
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                user:
                  description: username
                  type: string
                email:
                  description: email
                  type: string
                session:
                  description: session token
                  type: string
              required:
              - email
              - session
              - user
        required: true
      responses:
        "200":
          content: {}
          description: true/false
        "405":
          content: {}
          description: Invalid input
      summary: Updates a pet in the store with form data
      x-contentType: application/x-www-form-urlencoded
      x-accepts: application/json
components:
  schemas: {}
x-original-swagger-version: "2.0"

